# Generated by Django 4.1.2 on 2022-10-26 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='email',
        ),
    ]
