# Generated by Django 4.1.2 on 2022-10-26 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='issued',
            field=models.DateTimeField(null=True),
        ),
    ]
