# Generated by Django 4.1.2 on 2022-10-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_image1_product_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='circumference',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
