# Generated by Django 4.1.2 on 2022-10-28 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_product_circumference_product_size_product_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(null=True, upload_to='uploads'),
        ),
    ]
